DOC-59
JupiterOne/graph-gitlab pull request #69
Opened 2022-03-07 20:19 UTC by janettelynch

Customer-suggested edits.

2022-03-07 20:43 UTC, austinkelleher requested changes
Thanks for the improvements. Left a few comments.

2022-03-07 20:43 UTC, austinkelleher commented on docs/jupiterone.md
> +# Gitlab Integration with JupiterOne
```suggestion
# GitLab Integration with JupiterOne
```

2022-03-07 20:43 UTC, austinkelleher commented on docs/jupiterone.md
> +- Visualize GitLab users, groups, code repositories, and merge requests in the JupiterOne graph.
Our Markdown file format standard has a line width of 80 characters. Can you explain the motivation behind placing this all on a single line?

2022-03-07 20:43 UTC, austinkelleher commented on docs/jupiterone.md
> +- Visualize GitLab users, groups, code repositories, and merge requests in the JupiterOne graph.
Noticing that this change was made across multiple lines...

2022-03-07 20:43 UTC, austinkelleher commented on docs/jupiterone.md
> +- Enter the **API Base URL** (such as https://gitlab.com) of your self-managed GitLab instance.
👍

2022-03-09 22:00 UTC, janettelynch commented on docs/jupiterone.md
> +- Visualize GitLab users, groups, code repositories, and merge requests in the JupiterOne graph.
The 80-character limit was done to accommodate Zendesk's rendering of MD files. We no longer need these truncated lines in Vanilla. When the MD is rendered as HTML, Vanilla shows them as hard returns.

2022-03-10 02:23 UTC, austinkelleher commented on docs/jupiterone.md
> +- Visualize GitLab users, groups, code repositories, and merge requests in the JupiterOne graph.
@janettelynch to clarify, the 80 character line length is a code style that **we have adopted internally.** Our code formatting tool automatically formats the Markdown files this way. 

The next time our code formatter runs, it will automatically produce the newlines after 80 characters and undo the changes that you've made. Can you please undo the formatting changes that you've made? Thanks!

2022-03-10 14:06 UTC, janettelynch commented on docs/jupiterone.md
> +- Visualize GitLab users, groups, code repositories, and merge requests in the JupiterOne graph.
Sure, I can undo the changes. However, do you know why you adopted this short line length? It makes the articles much longer, forcing users to scroll more, which is not the best UX. We are undoing the truncated lines in the rest of the documentation for better usability and because we don't have the limitations that Zendesk put on us. It would be good to have the same style throughout all the documentation.
cc @AnneNielsenJ1

2022-03-10 14:50 UTC, austinkelleher commented on docs/jupiterone.md
> +- Visualize GitLab users, groups, code repositories, and merge requests in the JupiterOne graph.
@janettelynch This seems like a formatting problem with our documentation website. 80 character line length is used for nearly every code file in our entire organization. It's a length that is supposed to make it easier to view code in text editors. Our development tooling **automatically** formats our code files this way.

I think that our documentation website tooling should automatically format the Markdown in the desired form before shipping to Vanilla.

2022-03-10 14:53 UTC, austinkelleher approved these changes

2022-03-10 15:59 UTC, merged

2023-05-15 20:58 UTC, j1-internal-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v4.5.0`](https://github.com/JupiterOne/graph-gitlab/releases/tag/v4.5.0) :rocket: